// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package enumpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DayOfTheWeek int32

const (
	DayOfTheWeek_UNKNOWN   DayOfTheWeek = 0
	DayOfTheWeek_MONDAY    DayOfTheWeek = 1
	DayOfTheWeek_TUESDAY   DayOfTheWeek = 2
	DayOfTheWeek_WEDNESDAY DayOfTheWeek = 3
	DayOfTheWeek_THURSDAY  DayOfTheWeek = 4
	DayOfTheWeek_FRIDAY    DayOfTheWeek = 5
	DayOfTheWeek_SATURDAY  DayOfTheWeek = 6
	DayOfTheWeek_SUNDAY    DayOfTheWeek = 7
)

var DayOfTheWeek_name = map[int32]string{
	0: "UNKNOWN",
	1: "MONDAY",
	2: "TUESDAY",
	3: "WEDNESDAY",
	4: "THURSDAY",
	5: "FRIDAY",
	6: "SATURDAY",
	7: "SUNDAY",
}

var DayOfTheWeek_value = map[string]int32{
	"UNKNOWN":   0,
	"MONDAY":    1,
	"TUESDAY":   2,
	"WEDNESDAY": 3,
	"THURSDAY":  4,
	"FRIDAY":    5,
	"SATURDAY":  6,
	"SUNDAY":    7,
}

func (x DayOfTheWeek) String() string {
	return proto.EnumName(DayOfTheWeek_name, int32(x))
}

func (DayOfTheWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

type EnumMessage struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DayOfTheWeek         DayOfTheWeek `protobuf:"varint,2,opt,name=day_of_the_week,json=dayOfTheWeek,proto3,enum=protobuf.enum.DayOfTheWeek" json:"day_of_the_week,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnumMessage) GetDayOfTheWeek() DayOfTheWeek {
	if m != nil {
		return m.DayOfTheWeek
	}
	return DayOfTheWeek_UNKNOWN
}

func init() {
	proto.RegisterEnum("protobuf.enum.DayOfTheWeek", DayOfTheWeek_name, DayOfTheWeek_value)
	proto.RegisterType((*EnumMessage)(nil), "protobuf.enum.EnumMessage")
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor_13a9f1b5947140c8) }

var fileDescriptor_13a9f1b5947140c8 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcd, 0x2b, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0x53, 0x49, 0xa5, 0x69, 0x7a, 0x20, 0x41,
	0xa5, 0x44, 0x2e, 0x6e, 0xd7, 0xbc, 0xd2, 0x5c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21,
	0x27, 0x2e, 0xfe, 0x94, 0xc4, 0xca, 0xf8, 0xfc, 0xb4, 0xf8, 0x92, 0x8c, 0xd4, 0xf8, 0xf2, 0xd4,
	0xd4, 0x6c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x69, 0x3d, 0x14, 0x73, 0xf4, 0x5c, 0x12,
	0x2b, 0xfd, 0xd3, 0x42, 0x32, 0x52, 0xc3, 0x53, 0x53, 0xb3, 0x83, 0x78, 0x52, 0x90, 0x78, 0x5a,
	0xe5, 0x5c, 0x3c, 0xc8, 0xb2, 0x42, 0xdc, 0x5c, 0xec, 0xa1, 0x7e, 0xde, 0x7e, 0xfe, 0xe1, 0x7e,
	0x02, 0x0c, 0x42, 0x5c, 0x5c, 0x6c, 0xbe, 0xfe, 0x7e, 0x2e, 0x8e, 0x91, 0x02, 0x8c, 0x20, 0x89,
	0x90, 0x50, 0xd7, 0x60, 0x10, 0x87, 0x49, 0x88, 0x97, 0x8b, 0x33, 0xdc, 0xd5, 0xc5, 0x0f, 0xc2,
	0x65, 0x16, 0xe2, 0xe1, 0xe2, 0x08, 0xf1, 0x08, 0x0d, 0x02, 0xf3, 0x58, 0x40, 0xba, 0xdc, 0x82,
	0x3c, 0x41, 0x6c, 0x56, 0x90, 0x4c, 0xb0, 0x63, 0x48, 0x68, 0x10, 0x88, 0xc7, 0x06, 0x92, 0x09,
	0x0e, 0x05, 0x9b, 0xc7, 0xee, 0xc4, 0x11, 0xc5, 0x06, 0x72, 0x5b, 0x41, 0x52, 0x12, 0x1b, 0xd8,
	0xb1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x97, 0x52, 0x60, 0x09, 0x01, 0x00, 0x00,
}
